export interface Personagem {
  nome: string;
  dificuldade: 'facil' | 'medio' | 'dificil';
}

export const PERSONAGENS: Personagem[] = [
  // Fácil
  { nome: 'Adão', dificuldade: 'facil' },
  { nome: 'Eva', dificuldade: 'facil' },
  { nome: 'Noé', dificuldade: 'facil' },
  { nome: 'Abraão', dificuldade: 'facil' },
  { nome: 'Sara', dificuldade: 'facil' },
  { nome: 'Isaque', dificuldade: 'facil' },
  { nome: 'Jacó', dificuldade: 'facil' },
  { nome: 'José (filho de Jacó)', dificuldade: 'facil' },
  { nome: 'Moisés', dificuldade: 'facil' },
  { nome: 'Arão', dificuldade: 'facil' },
  { nome: 'Davi', dificuldade: 'facil' },
  { nome: 'Salomão', dificuldade: 'facil' },
  { nome: 'Sansão', dificuldade: 'facil' },
  { nome: 'Samuel', dificuldade: 'facil' },
  { nome: 'Jonas', dificuldade: 'facil' },
  { nome: 'Daniel', dificuldade: 'facil' },
  { nome: 'Jesus', dificuldade: 'facil' },
  { nome: 'Maria (mãe de Jesus)', dificuldade: 'facil' },
  { nome: 'Pedro', dificuldade: 'facil' },
  { nome: 'Paulo', dificuldade: 'facil' },
  { nome: 'João Batista', dificuldade: 'facil' },
  { nome: 'Maria Madalena', dificuldade: 'facil' },
  { nome: 'Rute', dificuldade: 'facil' },
  { nome: 'Dalila', dificuldade: 'facil' },
  { nome: 'Golias', dificuldade: 'facil' },

  // Médio
  { nome: 'Rebeca', dificuldade: 'medio' },
  { nome: 'Lia', dificuldade: 'medio' },
  { nome: 'Raquel', dificuldade: 'medio' },
  { nome: 'Josué', dificuldade: 'medio' },
  { nome: 'Gedeão', dificuldade: 'medio' },
  { nome: 'Boaz', dificuldade: 'medio' },
  { nome: 'Ester', dificuldade: 'medio' },
  { nome: 'Naamã', dificuldade: 'medio' },
  { nome: 'Eliseu', dificuldade: 'medio' },
  { nome: 'Elias', dificuldade: 'medio' },
  { nome: 'Ezequias', dificuldade: 'medio' },
  { nome: 'Jeremias', dificuldade: 'medio' },
  { nome: 'Isaías', dificuldade: 'medio' },
  { nome: 'Zaqueu', dificuldade: 'medio' },
  { nome: 'Bartimeu', dificuldade: 'medio' },
  { nome: 'Nicodemos', dificuldade: 'medio' },
  { nome: 'Marta', dificuldade: 'medio' },
  { nome: 'Lázaro', dificuldade: 'medio' },
  { nome: 'Barnabé', dificuldade: 'medio' },
  { nome: 'Estêvão', dificuldade: 'medio' },
  { nome: 'Jonatã', dificuldade: 'medio' },
  { nome: 'Débora', dificuldade: 'medio' },
  { nome: 'Saul (rei de Israel)', dificuldade: 'medio' },
  { nome: 'Noemi', dificuldade: 'medio' },
  { nome: 'Jó', dificuldade: 'medio' },

  // Difícil
  { nome: 'Melquisedeque', dificuldade: 'dificil' },
  { nome: 'Aitofel', dificuldade: 'dificil' },
  { nome: 'Jeú', dificuldade: 'dificil' },
  { nome: 'Obadias', dificuldade: 'dificil' },
  { nome: 'Amós', dificuldade: 'dificil' },
  { nome: 'Oseias', dificuldade: 'dificil' },
  { nome: 'Habacuque', dificuldade: 'dificil' },
  { nome: 'Sofonias', dificuldade: 'dificil' },
  { nome: 'Ageu', dificuldade: 'dificil' },
  { nome: 'Malaquias', dificuldade: 'dificil' },
  { nome: 'Zorobabel', dificuldade: 'dificil' },
  { nome: 'Esdras', dificuldade: 'dificil' },
  { nome: 'Neemias', dificuldade: 'dificil' },
  { nome: 'Filemom', dificuldade: 'dificil' },
  { nome: 'Silas', dificuldade: 'dificil' },
  { nome: 'Manaém', dificuldade: 'dificil' },
  { nome: 'Icabode', dificuldade: 'dificil' },
  { nome: 'Zedequias', dificuldade: 'dificil' },
  { nome: 'Mordecai', dificuldade: 'dificil' },
  { nome: 'Hamã', dificuldade: 'dificil' },
  { nome: 'Ezequiel', dificuldade: 'dificil' },
  { nome: 'Naum', dificuldade: 'dificil' },
  { nome: 'Jefté', dificuldade: 'dificil' },
  { nome: 'Elcana', dificuldade: 'dificil' },
  { nome: 'Abimeleque', dificuldade: 'dificil' },
];
