// <auto-generated />
using System;
using JogoBiblicoBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JogoBiblicoBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501180000_AdminReportsSuggestions")]
    partial class AdminReportsSuggestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("JogoBiblicoBackend.Models.QuestionReport", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("Contexto").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Detalhe").HasColumnType("TEXT");
                    b.Property<string>("Modo").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Motivo").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PerguntaId").HasColumnType("TEXT");
                    b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAt");
                    b.HasIndex("Status");
                    b.ToTable("QuestionReports");
                });

            modelBuilder.Entity("JogoBiblicoBackend.Models.QuestionSuggestion", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("AlternativaA").HasColumnType("TEXT");
                    b.Property<string>("AlternativaB").HasColumnType("TEXT");
                    b.Property<string>("AlternativaC").HasColumnType("TEXT");
                    b.Property<string>("AlternativaD").HasColumnType("TEXT");
                    b.Property<string>("Contato").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Dificuldade").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Nome").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Observacao").HasColumnType("TEXT");
                    b.Property<string>("Pergunta").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Referencia").HasColumnType("TEXT");
                    b.Property<string>("RespostaCorreta").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Testamento").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAt");
                    b.HasIndex("Status");
                    b.ToTable("QuestionSuggestions");
                });

            modelBuilder.Entity("JogoBiblicoBackend.Models.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("IsAdmin").HasColumnType("INTEGER");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
